"""Initial migration

Revision ID: 8af2d735d922
Revises: 
Create Date: 2024-10-05 10:47:24.365964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8af2d735d922'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'projects',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('title', sa.String(length=255), nullable=False, index=True),
        sa.Column('url', sa.String(length=2083), nullable=False, index=True),
        sa.Column('company', sa.String(length=255), nullable=True, index=True),
        sa.Column('problem', sa.Text, nullable=True),
        sa.Column('solution', sa.Text, nullable=True),
        sa.Column('tags', sa.ARRAY(sa.String), nullable=True)
    )

    # Создание GIN индексов для столбцов 'problem' и 'solution' с использованием триграммного поиска
    op.execute('CREATE INDEX idx_problem_gin ON projects USING gin (problem gin_trgm_ops)')
    op.execute('CREATE INDEX idx_solution_gin ON projects USING gin (solution gin_trgm_ops)')
    op.execute('CREATE INDEX idx_tags_gin ON projects USING gin (tags)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tags_gin', table_name='projects')
    op.drop_index('idx_solution_gin', table_name='projects')
    op.drop_index('idx_problem_gin', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
