"""Add embedding column to projects

Revision ID: 662e485f6e02
Revises: f7a79b5180d6
Create Date: 2024-10-12 10:27:40.400207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '662e485f6e02'
down_revision: Union[str, None] = 'f7a79b5180d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('embedding', sa.ARRAY(sa.Float), nullable=True))
    # op.add_column('projects', sa.Column('embedding_tags', sa.ARRAY(sa.Float), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'embedding')
    # op.drop_column('projects', 'embedding_tags')
    # ### end Alembic commands ###
