"""Fill embeddings for projects

Revision ID: d38341733b04
Revises: 662e485f6e02
Create Date: 2024-10-12 10:37:31.972967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import Session
from sentence_transformers import SentenceTransformer

# revision identifiers, used by Alembic.
revision: str = 'd38341733b04'
down_revision: Union[str, None] = '662e485f6e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

model = SentenceTransformer('paraphrase-MiniLM-L6-v2')
# model = SentenceTransformer('distiluse-base-multilingual-cased-v2')
# model = SentenceTransformer('bert-base-nli-mean-tokens')



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    projects = session.execute(sa.text("SELECT id, title, company, tags FROM projects")).fetchall()
    for project in projects:
        project_text = f"{project.title} {project.company} {' '.join(project.tags) if project.tags else ''}"
        
        project_embedding = model.encode(project_text).tolist()
        
        session.execute(
            sa.text("UPDATE projects SET embedding = :embedding WHERE id = :id"),
            {"embedding": project_embedding, "id": project.id}
        )

    session.commit()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    session.execute(sa.text("UPDATE projects SET embedding = NULL"))
    session.commit()
    # ### end Alembic commands ###
